from __future__ import annotations

from pathlib import Path
from typing import Any

from core.utils import write_text


def _fmt_metric(value) -> str:
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


def _quality_table(quality: dict[str, Any]) -> str:
    lines = []
    lines.append(f"**Total checks:** {quality.get('total_checks', 0)} | "
                 f"**Passed:** {quality.get('passed', 0)} | "
                 f"**Failed:** {quality.get('failed', 0)} | "
                 f"**Success rate:** {quality.get('success_rate', 0):.1%}")
    lines.append("")
    lines.append("| Check | Status | Detail |")
    lines.append("|-------|--------|--------|")
    for check in quality.get("checks", []):
        status_icon = "✅" if check["status"] == "PASS" else "❌"
        lines.append(f"| {check['check']} | {status_icon} {check['status']} | {check['detail']} |")
    return "\n".join(lines)


def _freshness_section(freshness: dict[str, Any]) -> str:
    is_fresh = freshness.get("is_fresh", False)
    lines = [
        f"- **Latest published:** {freshness.get('latest_published', 'N/A')}",
        f"- **Oldest published:** {freshness.get('oldest_published', 'N/A')}",
        f"- **Stale rows:** {freshness.get('stale_rows', 0)} / {freshness.get('total_rows', 0)}",
        f"- **Freshness threshold:** {freshness.get('freshness_threshold_days', 180)} days",
        f"- **Status:** {'✅ FRESH' if is_fresh else '⚠️ STALE'}",
    ]
    return "\n".join(lines)


def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    """Viết markdown report cho baseline phase."""
    report_path = Path(report_path)

    lines = [
        "# Phase 1 Baseline Pipeline Report",
        "",
        "## 1. Data Source",
        "",
        f"- **API:** {source_summary.get('source_api', 'Crossref REST API')}",
        f"- **Query:** `{source_summary.get('source_query', '')}`",
        f"- **Filter:** `{source_summary.get('source_filter', '')}`",
        f"- **Raw records fetched:** {source_summary.get('raw_count', 'N/A')}",
        f"- **Clean records:** {source_summary.get('clean_count', 'N/A')}",
        "",
        "## 2. Evaluation Metrics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Samples | {metrics.get('samples', 'N/A')} |",
        f"| Retrieval Hit Rate | {_fmt_metric(metrics.get('retrieval_hit_rate', 'N/A'))} |",
        f"| Mean Token F1 | {_fmt_metric(metrics.get('mean_token_f1', 'N/A'))} |",
        f"| Judge Accuracy | {_fmt_metric(metrics.get('judge_accuracy', 'N/A'))} |",
        f"| Mean Judge Score | {_fmt_metric(metrics.get('mean_judge_score', 'N/A'))} |",
        "",
    ]

    ragas = metrics.get("ragas", {})
    if ragas and "skipped" not in ragas and "error" not in ragas:
        lines += [
            "### RAGAS Metrics",
            "",
            "| Metric | Value |",
            "|--------|-------|",
        ]
        for k, v in ragas.items():
            lines.append(f"| {k} | {_fmt_metric(v)} |")
        lines.append("")

    lines += [
        "## 3. Data Quality Checks",
        "",
        _quality_table(quality),
        "",
        "## 4. Data Freshness",
        "",
        _freshness_section(freshness),
        "",
        "---",
        "_Report generated by Day 10 Data Observability Pipeline_",
    ]

    write_text(report_path, "\n".join(lines))
    print(f"Phase 1 report saved to {report_path}")


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    """Viết markdown report so sánh baseline/corrupted/repaired."""
    report_path = Path(report_path)

    def delta(baseline_val, other_val) -> str:
        try:
            b = float(baseline_val)
            o = float(other_val)
            diff = o - b
            sign = "+" if diff >= 0 else ""
            return f"{sign}{diff:.4f}"
        except Exception:
            return "N/A"

    metric_keys = ["retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score"]

    lines = [
        "# Corruption & Repair Comparison Report",
        "",
        "## Overview",
        "",
        "This report compares agent performance across three pipeline states:",
        "- **Baseline**: clean data",
        "- **Corrupted**: data with injected errors",
        "- **Repaired**: data restored from raw source",
        "",
        "## Metric Comparison",
        "",
        "| Metric | Baseline | Corrupted | Δ Corrupt | Repaired | Δ Repair |",
        "|--------|----------|-----------|-----------|----------|----------|",
    ]

    for key in metric_keys:
        b = baseline_metrics.get(key, "N/A")
        c = corrupted_metrics.get(key, "N/A")
        r = repaired_metrics.get(key, "N/A")
        d_corrupt = delta(b, c)
        d_repair = delta(b, r)
        lines.append(
            f"| {key} | {_fmt_metric(b)} | {_fmt_metric(c)} | {d_corrupt} | {_fmt_metric(r)} | {d_repair} |"
        )

    lines += [
        "",
        "## Data Quality: Corrupted vs Repaired",
        "",
        "### Corrupted Data Quality",
        "",
        _quality_table(corrupted_quality),
        "",
        "### Repaired Data Quality",
        "",
        _quality_table(repaired_quality),
        "",
        "## Freshness: Corrupted vs Repaired",
        "",
        "### Corrupted Freshness",
        "",
        _freshness_section(corrupted_freshness),
        "",
        "### Repaired Freshness",
        "",
        _freshness_section(repaired_freshness),
        "",
        "## Analysis",
        "",
    ]

    # Auto-analysis
    try:
        b_hr = float(baseline_metrics.get("retrieval_hit_rate", 0))
        c_hr = float(corrupted_metrics.get("retrieval_hit_rate", 0))
        r_hr = float(repaired_metrics.get("retrieval_hit_rate", 0))
        if c_hr < b_hr:
            lines.append(f"- ⚠️ Corruption **decreased** retrieval hit rate by {b_hr - c_hr:.4f} ({(b_hr-c_hr)/b_hr*100:.1f}%).")
        if r_hr >= b_hr * 0.95:
            lines.append(f"- ✅ Repair **restored** retrieval hit rate to {r_hr:.4f} (baseline: {b_hr:.4f}).")
        elif r_hr > c_hr:
            lines.append(f"- ↗️ Repair **improved** hit rate from {c_hr:.4f} to {r_hr:.4f} (partial recovery).")
    except Exception:
        pass

    lines += [
        "",
        "---",
        "_Report generated by Day 10 Data Observability Pipeline_",
    ]

    write_text(report_path, "\n".join(lines))
    print(f"Corruption comparison report saved to {report_path}")
